# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

GOOGLE_APP_ID: "1040164547033-5v4teb15ujn2dhp4ug9pel7n7su7ck0k.apps.googleusercontent.com"
GOOGLE_APP_SECRET: "gzwgxY9MMf6Ye9UEQSK_utuq"

AWS_ACCESS_KEY_ID: "AKIAJ7GJ67NXI43S3NRA" 
AWS_SECRET_ACCESS_KEY: "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" 
S3_BUCKET: "Instagaram"